[app]
idle-timeout = 5 # As Seconds
name = "API Boilerplate" 
port = ":8080" 
prefork = true 
print-routes = false 
production = false 

[app.tls]
cert-file = "./storage/selfsigned.crt"
enable = false
key-file = "./storage/selfsigned.key"

[db.mysql]
dsn = "" # <username>:<password>@<host><port>/<database>

[logger]
level = 0 # panic -> 5, fatal -> 4, error -> 3, warn -> 2, info -> 1, debug -> 0, trace -> -1
prettier = true 
time-format = "" 

[middleware.compress]
enable = true
level = 1

[middleware.recover]
enable = true

[middleware.monitor]
enable = false
path = "/monitor"

[middleware.pprof]
enable = true

[middleware.limiter]
enable = false
expiration_seconds = 60
max = 20

[middleware.filesystem]
browse = true
enable = false
index = "index.html"
max_age = 3600
root = "./storage/public"
